### ISSUE TITLE
[Clearpath Ridgeback R100] Robot Yaw and Y-axis Inverted

### ISSUE THREAD

**Issue by SOHAILMBS** [clearpathrobotics/clearpath_common#103]
**Please provide the following information:**
 - OS: (e.g. Ubuntu 22.04) Ubuntu 22
 - ROS 2 Distro: (e.g. Humble) Humble
 - Built from source or installed: Installed
 - Package version: 

Package: ros-humble-clearpath-common
Status: install ok installed
Priority: optional
Section: misc
Installed-Size: 42
Maintainer: Luis Camero <lcamero@clearpathrobotics.com>
Architecture: amd64
Version: 0.3.4-1jammy.20241009.173302
Depends: ros-humble-clearpath-control, ros-humble-clearpath-description, ros-humble-clearpath-generator-common, ros-humble-clearpath-platform, ros-humble-ros-workspace
Description: Clearpath Common Metapackage

 - Real hardware or simulation: Real

 **Expected behaviour**
When moving Ridgeback in y direction, it moves in y-direction.

 **Actual behaviour**
X movement is correct, Y is performing yaw movement, and yaw is performing Y movement.

**To Reproduce**
Provide the steps to reproduce:
1. Visualize via RViz2 or echo  topic ` ros2 topic echo /r100_0118/platform/odom`

**Comment by SOHAILMBS** [comment]
The issue was from the joystick giving inverted commands. Clearpath has now switched yaw and y-axis which it previously was in ROS Noetic.

**Comment by SOHAILMBS** [comment]
It seems it is not from the joy stick but happening from the teleop_twist_keyboard as well. For some some reason the y and yaw are inverted

**Comment by tonybaltovski** [comment]
Is this the input from the tele-op or cmd_vel that is causing the behaviour?

**Comment by SOHAILMBS** [comment]
Dear @tonybaltovski,

The issue is resolved. It occurred due to a production fault in which two of the omni wheels were facing outwards.
