### ISSUE TITLE
[Clearpath Ridgeback R100] Fix rear lights color

### ISSUE THREAD

**Issue by SOHAILMBS** [clearpathrobotics/clearpath_common#105]
**Please provide the following information:**

OS: (e.g. Ubuntu 22.04) Ubuntu 22
ROS 2 Distro: (e.g. Humble) Humble
Built from source or installed: Installed
Package version:
Package: ros-humble-clearpath-common
Status: install ok installed
Priority: optional
Section: misc
Installed-Size: 42
Maintainer: Luis Camero [lcamero@clearpathrobotics.com](mailto:lcamero@clearpathrobotics.com)
Architecture: amd64
Version: 0.3.4-1jammy.20241009.173302
Depends: ros-humble-clearpath-control, ros-humble-clearpath-description, ros-humble-clearpath-generator-common, ros-humble-clearpath-platform, ros-humble-ros-workspace
Description: Clearpath Common Metapackage

**Real hardware or simulation:** 
Real

**Expected behaviour**
Rear lights are red

**Actual behaviour**
Rear lights are black

**To Reproduce**
Visualize via RViz2 

**Solution**
Update `clearpath_platform_description/urdf/r100/r100.urdf.xacro ` link rear_lights_link from clearpath_black to clearpath_red

**Comment by tonybaltovski** [comment]
Thanks for reporting this!
