### ISSUE TITLE
IMU data not included in localization yaml

### ISSUE THREAD

**Issue by immanueln98** [clearpathrobotics/clearpath_common#115]
Hi there. 
When going through the platform API, it states that the odom/filtered is fused with IMU datam however, when I inspect the localization yaml for the ekf node settings, I seem to only see wheel odometry being included as shown in the image. Is this the case, or could I be mistaken?

![image](https://github.com/user-attachments/assets/97ab01aa-b2be-408d-bc8d-836e5a2477a2)

**Comment by roni-kreinin** [comment]
This is the default localization yaml. When you add an IMU to your `robot.yaml` file it will be added to the generated localization yaml.

See https://github.com/clearpathrobotics/clearpath_common/blob/9f8e5375c747fcbc5c4c40c7b7f911c30ab5ca57/clearpath_generator_common/clearpath_generator_common/param/platform.py#L203
